In [1]:
import torch
import torch.nn as nn


In [2]:
# Example input: batch_size=1, sequence_length=4
x = torch.tensor([[1, 2, 3, 4]])



In [4]:
#2. Embedding Layer
# ------------------------------------

vocab_size = 10
embed_size = 8

embedding = nn.Embedding(vocab_size, embed_size)

embedded = embedding(x)

print("Embedded Input:\n", embedded)

Embedded Input:
 tensor([[[-0.3883,  0.7629, -0.4625, -0.1566, -1.1788, -0.2494,  1.2785,
           1.1158],
         [-1.1135,  0.9610,  1.4495, -0.5849, -0.7894, -1.5278, -0.3887,
           0.9350],
         [-1.2177,  1.8157, -2.5099, -1.1004,  2.7490,  0.4455, -1.2528,
           0.5405],
         [-0.9142, -1.1475, -0.5644,  1.0463,  0.8018, -0.8246,  0.8343,
           0.0165]]], grad_fn=<EmbeddingBackward0>)


In [5]:
# 3. Multihead Attention
# ------------------------------------

attention = nn.MultiheadAttention(
    embed_dim=embed_size,
    num_heads=2,
    batch_first=True
)

attention_output, attention_weights = attention(
    embedded,
    embedded,
    embedded
)

print("\nAttention Output:\n", attention_output)




Attention Output:
 tensor([[[ 0.0038,  0.0031,  0.3474, -0.0980,  0.2311, -0.0182, -0.0086,
          -0.3551],
         [-0.0514,  0.0323,  0.3036, -0.0420,  0.2015, -0.0858,  0.0355,
          -0.2976],
         [ 0.4024, -0.3117,  0.4479, -0.3330,  0.2604,  0.4801, -0.0061,
          -0.6869],
         [-0.1144, -0.0328,  0.0999, -0.1134,  0.0156, -0.0941,  0.0472,
          -0.0368]]], grad_fn=<TransposeBackward0>)


In [6]:
# ------------------------------------
# 4. Feed Forward Network
# ------------------------------------

feed_forward = nn.Sequential(
    nn.Linear(embed_size, 16),
    nn.ReLU(),
    nn.Linear(16, embed_size)
)

ff_output = feed_forward(attention_output)

print("\nFeed Forward Output:\n", ff_output)



Feed Forward Output:
 tensor([[[ 0.0404, -0.1677,  0.0361, -0.0547,  0.1761,  0.0748, -0.3370,
           0.2492],
         [ 0.0329, -0.1464,  0.0361, -0.0679,  0.1658,  0.0855, -0.3060,
           0.2381],
         [ 0.0441, -0.2307, -0.0235,  0.0194,  0.2557,  0.0581, -0.4641,
           0.3097],
         [ 0.0152, -0.1124,  0.0173, -0.0926,  0.1279,  0.0829, -0.2145,
           0.2111]]], grad_fn=<ViewBackward0>)


In [7]:
# 5. Final Transformer Block
# ------------------------------------

class SimpleTransformer(nn.Module):

    def __init__(self):
        super(SimpleTransformer, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embed_size)

        self.attention = nn.MultiheadAttention(
            embed_dim=embed_size,
            num_heads=2,
            batch_first=True
        )

        self.ff = nn.Sequential(
            nn.Linear(embed_size, 16),
            nn.ReLU(),
            nn.Linear(16, embed_size)
        )

    def forward(self, x):

        x = self.embedding(x)

        attn_output, _ = self.attention(x, x, x)

        output = self.ff(attn_output)

        return output



In [8]:
# 6. Create Model
# ------------------------------------

model = SimpleTransformer()

output = model(x)

print("\nFinal Transformer Output:\n", output)


Final Transformer Output:
 tensor([[[-0.0299,  0.1454,  0.0402,  0.0189, -0.1207,  0.1755,  0.1609,
          -0.1866],
         [-0.0280,  0.1468,  0.0374,  0.0252, -0.1220,  0.1654,  0.1531,
          -0.1795],
         [-0.0345,  0.1400,  0.0493,  0.0241, -0.1293,  0.1726,  0.1573,
          -0.1819],
         [-0.0318,  0.1456,  0.0454,  0.0181, -0.1225,  0.1804,  0.1620,
          -0.1898]]], grad_fn=<ViewBackward0>)
